apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hazelcast-operator
  template:
    metadata:
      labels:
        name: hazelcast-operator
    spec:
      serviceAccountName: hazelcast-operator
      containers:
        - name: hazelcast-operator
          # Replace this with the built image name
          image: stakater/hazelcast-operator:1.0.1
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hazelcast-operator"
